CREATE TABLE IF NOT EXISTS genre (
	genre_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS mpa_rating (
	mpa_rating_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(10) NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS films (
	film_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL CHECK (name <> ''),
	description VARCHAR(200) CHECK (description <> ''),
	release_date DATE CHECK(release_date >= DATE '1895-12-28'),
	duration INTEGER NOT NULL CHECK(duration > 0),
	mpa_rating_id INTEGER NOT NULL REFERENCES mpa_rating(mpa_rating_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS films_genre (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	film_id BIGINT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE ON UPDATE CASCADE,
	genre_id INTEGER NOT NULL REFERENCES genre(genre_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (film_id, genre_id)
);


CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(50) NOT NULL CHECK (email <> '') UNIQUE,
	login VARCHAR(50) NOT NULL CHECK (login <> ''),
	name VARCHAR(50) NOT NULL CHECK (name <> ''),
	birthday DATE
);

CREATE TABLE IF NOT EXISTS film_likes (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	film_id BIGINT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	sender BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	receiver BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (sender, receiver)
);
